"$schema" = "https://starship.rs/config-schema.json"

format = "$python$username$hostname$directory$git_branch$git_status$git_metrics$status$character"
right_format = "$cmd_duration$memory_usage"
add_newline = false
palette = "catppuccin_mocha"

[python]
format = "[\\($virtualenv\\) ]($style)"
style = "blue"

[username]
format = "[$user]($style)"
style_user = "green"
show_always = true

[hostname]
format = "@$hostname "
ssh_only = false

[directory]
format = "in [$path]($style) "
style = "green"

[git_branch]
style = "yellow"

[git_status]
style = "red"

[git_metrics]
added_style = "green"
deleted_style = "red"
disabled = false

[status]
format = "[\\[$status\\] ]($style)"
style = "red"
disabled = false

[character]
format = "$symbol "
success_symbol = "\\$"
error_symbol = "\\$"

[cmd_duration]
format = "took [$duration]($style)"
style = "blue"

[memory_usage]
format = " via [$ram]($style)"
style = "blue"
disabled = false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
