import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 140, lines = 35 }
padding = { x = 16, y = 16 }
decorations = "Buttonless"
opacity = 1
blur = false

[font]
normal.family = "Iosevka Nerd Font"
size = 16
